# Generated by Django 3.1.3 on 2020-12-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
